FROM dylanmei/zeppelin

#ADD lib/mysql-connector-java-5.1.40-bin.jar $ZEPPELIN_HOME/lib/mysql-connector-java-5.1.40-bin.jar
#ADD lib/presto-jdbc-0.165.jar $ZEPPELIN_HOME/lib/presto-jdbc-0.165.jar
# Las lineas anteriores no parece que funcionen, no ponen los jar en el classpath correcto
